### ISSUE TITLE
WAUTH-2 and WA 1.5 todo before merging

### ISSUE THREAD

**Issue by matteocontrini** [hidespb/node-whatsapi#27]
Currently, the WAUTH-2 with WA 1.5 implementation is in progress in a separate branch. The status of the work can be found [here](https://github.com/hidespb/node-whatsapi/issues/23).

Things to do before merging in the master branch:

- [x] Create a new legacy branch with the old WAUTH-1 implementation
- [x] Callbacks instead of events when appropriate
 - [x] Callbacks parameters commented
- Check JSDoc consistency between comments
 - [x] No return value --> no @return or @returns
 - [x] The type should be written uppercase (String, not string) in @property
 - [x] @fires for functions emitting an event
 - [x] Events should be commented (@event)
- [x] Code quality
 - [x] Event names should be camelCase
 - [x] Event should pass an object as parameter, when appropriate (i.e. a group)
- [x] Write proper documentation
 - [x] Converted JSDoc
 - [x] Some additional examples
- [x] Update NPM package (v1.0)
- [x] [Badge](https://nodei.co/)

**Comment by matteocontrini** [comment]
The next version will be 1.0, and not 0.2.
[Guidelines](http://semver.org/).

**Comment by matteocontrini** [comment]
#45
